CREATE TABLE LINK_T_AMBULANCECALL_T_COMPLICATION
(
  DOCAID VARCHAR(32) REFERENCES T_AMBULANCECALL (ID) NOT NULL,
  DOCBID VARCHAR(32) REFERENCES T_COMPLICATION (ID) NOT NULL,
  CONSTRAINT P9B0AD7C3F6884ADE25GT83KJCGDS0
  PRIMARY KEY
  (DOCAID, DOCBID)
);
