CREATE TABLE T_SIGNATURE
(
  ID                     VARCHAR(32) PRIMARY KEY,
  STATE                  NUMERIC(10) NOT NULL,
  ACTIONDATE             TIMESTAMP(2)         NOT NULL,
  ACTIONUSERID           VARCHAR(32) NOT NULL,
  VERSIONID              NUMERIC(10) NOT NULL,
  STORAGEID              VARCHAR(32) NOT NULL,
  CREATEDATE             TIMESTAMP(2)         NOT NULL,
  CREATEUSERID           VARCHAR(32) NOT NULL,
  REFCOUNT               NUMERIC(10) NOT NULL,
  SIGNDATE               TIMESTAMP(2) ,
  EMPLOYEE_SIGNATURIES_1 VARCHAR(32)
);