CREATE TABLE LINK_T_AMBULANCECALL_T_AMBULANCECALLRELIEFACTION
(
  DOCAID VARCHAR(32) REFERENCES T_AMBULANCECALL (ID) NOT NULL,
  DOCBID VARCHAR(32) REFERENCES T_AMBULANCECALLRELIEFACTION (ID) NOT NULL,
  CONSTRAINT P5EE036F9BF0B45F9J47107777QSJ3
  PRIMARY KEY
  (DOCAID, DOCBID)
);
