CREATE TABLE T_AMBULANCECALLRELIEFACTION
(
  ID           VARCHAR(32) PRIMARY KEY NOT NULL,
  STATE        NUMERIC(10)             NOT NULL,
  ACTIONDATE   TIMESTAMP(2)            NOT NULL,
  ACTIONUSERID VARCHAR(32)             NOT NULL,
  VERSIONID    NUMERIC(10)             NOT NULL,
  STORAGEID    VARCHAR(32)             NOT NULL,
  CREATEDATE   TIMESTAMP(2)            NOT NULL,
  CREATEUSERID VARCHAR(32)             NOT NULL,
  REFCOUNT     NUMERIC(10)             NOT NULL,
  NAME         VARCHAR(255)
);