CREATE TABLE VDENUMTYPES
(
  ID             VARCHAR(16)  PRIMARY KEY NOT NULL,
  NAME           VARCHAR(128) NOT NULL,
  ALIAS          VARCHAR(64)  NOT NULL,
  REMARK         VARCHAR(1024),
  STYLE          NUMERIC(10)   NOT NULL,
  DEFAULTVALUEID VARCHAR(16),
  REFCOUNT       NUMERIC(10)   NOT NULL,
  ISLOCAL        NUMERIC(10)   NOT NULL
);