CREATE TABLE T_REFMKBDIAGNOSIS
(
  ID                      VARCHAR(32) PRIMARY KEY,
  STATE                   NUMERIC(10) NOT NULL,
  ACTIONDATE              DATE        NOT NULL,
  ACTIONUSERID            VARCHAR(32) NOT NULL,
  REFCOUNT                NUMERIC(10) NOT NULL,
  CODEXX                  NUMERIC(10),
  DESCRIPTION             CLOB,
  CODEY                   NUMERIC(10),
  DIAGNOSENAME            VARCHAR(255),
  CODEA                   VARCHAR(1),
  CODE                    VARCHAR(10),
  SYMBOL                  VARCHAR(255),
  REFMKBDIAGNOSIS_SUBDI_1 VARCHAR(32) REFERENCES T_REFMKBDIAGNOSIS (ID) ON DELETE SET NULL,
  REFMKBCLASS_REFDIAGNO_1 VARCHAR(32),
  VERSIONID               NUMERIC(10) NOT NULL,
  STORAGEID               VARCHAR(32) NOT NULL,
  CREATEDATE              DATE        NOT NULL,
  CREATEUSERID            VARCHAR(32) NOT NULL
);